name: handyman_provider_flutter
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  nb_utils: ^4.4.10
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  cached_network_image: ^3.1.0
  google_fonts: ^2.1.0
  flutter_vector_icons: ^1.0.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  date_time_picker: 2.1.0
  url_launcher: ^6.0.12
  flutter_rating_bar: ^4.0.0
  package_info: ^2.0.2
  google_mobile_ads: ^0.13.5

  #image:
  path_provider: ^2.0.6
  image_picker: ^0.8.4+3
  multi_image_picker: ^4.8.1
  photo_view: ^0.13.0
  file_picker: ^4.1.6
  image_cropper: any

  #notifications:
  onesignal_flutter: ^3.2.4

  #chart
  syncfusion_flutter_charts: ^19.3.47
  charts_flutter: ^0.11.0

  #map:
  geocoding: ^2.0.1

  #Firebase
  firebase_crashlytics: ^2.2.4
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  firebase_storage: ^10.0.6
  firebase_database: ^8.0.1
  paginate_firestore: ^1.0.2
  cloud_firestore: ^2.5.4
  firebase_messaging: any

  flutter_localizations:
    sdk: flutter
  video_player: ^2.4.2
  veriff_flutter: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  mobx_codegen: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flag/
    - images/video/splash2.mp4
